; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:t-beams3-supreme]
platform = espressif32
board = t-beams3-supreme
framework = arduino
monitor_port = /dev/cu.usbmodem1101
monitor_speed = 115200
build_flags =
	-D LED_ACTIVE_LOW
	-D LED_NEOPIXEL_GPIO=38
	-D LED_SWEEP_ENABLE
lib_deps = 
	TinyGPSPlus
	lewisxhe/SensorLib
	lewisxhe/XPowersLib
	olikraus/U8g2
